### ISSUE TITLE
Fails with "found two different crates with name `…`"

### ISSUE THREAD

**Issue by killercup** [ibabushkin/rust-semverver#32] opened 2017-09-07 14:55 UTC
I'm trying to run `cargo semver` on the `cargo-edit` crate and get a weird error.

> error[E0523]: found two different crates with name `memchr` that are not distinguished by differing `-C metadata`. This will result in symbol conflicts between the two.

You can reproduce it with:

```sh
$ rustc --version
rustc 1.21.0-nightly (e26688824 2017-08-27)
$ git clone https://github.com/killercup/cargo-edit
$ cd cargo-edit
$ git rev-parse HEAD # for the record
f40507d26bb73fc5a2200abb728727e4f5afa00c
$ cargo semver # from commit 4b4ce95
…
   Compiling cargo-edit v0.3.0-alpha.1 (file:///Users/pascal/Projekte/_resolved/cargo-edit)
…
    Finished dev [unoptimized + debuginfo] target(s) in 47.40 secs
…
       Fresh cargo-edit v0.3.0-alpha.1
    Finished dev [unoptimized + debuginfo] target(s) in 0.5 secs
error[E0523]: found two different crates with name `memchr` that are not distinguished by differing `-C metadata`. This will result in symbol conflicts between the two.
 --> <anon>:1:31
  |
1 | #[allow(unused_extern_crate)] extern crate new; #[allow(unused_extern_crate)] extern crate old;
  |
```

**Comment by ibabushkin** [comment] 2017-09-07 17:00
That's indeed rather odd - since we rename the crates when linking them together with the dummy. Thank you for your report, I'll have a look!

**Comment by ibabushkin** [comment] 2017-09-08 09:18
Hm, sadly, I wasn't able to reproduce it, it runs fine on the latest master and newest nightly at the time of writing:
```sh
$ rustc --version
rustc 1.22.0-nightly (368122087 2017-09-06)
$ git rev-parse HEAD # the rust-semverver verion
72854c541f8cfad9ddf419d3f472ea8c8d3f9dc4
```

runs as expected on a fresh checkout of `cargo-edit`. Could you try in that configuration again? And maybe try running with `RUST_LOG=debug RUST_BACKTRACE=full`, the output might give us valuable hints.

**Comment by ibabushkin** [comment] 2017-10-05 11:43
Okay, I was now able to reproduce it:

```
$ rustc --version
rustc 1.22.0-nightly (f1b5225e8 2017-10-01)
$ git rev-parse HEAD # cargo-edit (newest master at the time of writing)
3bb428bf1d4c38adfda874a1ae3f8d76ceaf0012
$ git rev-parse HEAD # rust-semverver (newest master at the time of writing)
f0a5bcda13b38868fb67117be6dfd676e068b5c0
```
So I can now have a look and report back what I find.

**Comment by killercup** [comment] 2017-10-05 11:55
Oh I'm so sorry, I totally forgot to follow up on this! Would it still help
if I give you more data?

Inokentiy Babushkin <notifications@github.com> schrieb am Do. 5. Okt. 2017
um 13:43:

**Comment by ibabushkin** [comment] 2017-10-05 12:03
Certainly! While I was able to reproduce it, it might be a one-time thing only (especially when I update things), so having data from your run (with debug output etc) would of course help.

**Comment by ibabushkin** [comment] 2017-10-05 13:26
So I conclude the following: Both `0.3.0-alpha.1` of `cargo-edit` and the current `master` transitively depend on `memchr-1.0.1`, but because the compilation procedure for both crates is independent, it seems that we wind up with two rlibs for `memchr`. Moreover, they have different hashes in their names (I believe, if I am interpreting everything correctly - I could be wrong on this). So when analysis starts, we try to depend on both versions of `cargo-edit`, pulling in both versions of `memchr`, which causes a name clash, because we don't rename transitive dependencies (as that'd be vastly overcomplicated). I'll try to build a minimal test case to reproduce this - since this doesn't happen with all crates.

**Comment by ibabushkin** [comment] 2017-10-07 10:37
Well, this is depressing: removing all build artifacts *sometimes* helps. This is also what makes it particularly tricky to reproduce this bug. So I think we should keep this workaround in mind and make proper logs of the next occurence of it.

**Comment by ibabushkin** [comment] 2017-10-07 11:17
It all boils down to two crates of the same version and name having different hashes. In this case both old and new crates link against `memchr-1.0.1`, but the rlibs of said crate have different hashes (the *same* metadata though) and are both linked in, causing a conflict. So essentially, the root of the problem is cargo rightfully assuming the same version of the same crate always has the same hash.

**Comment by Eijebong** [comment] 2018-01-21 21:04
Running `cargo semver` on the metadeps crate (with a bump to error-chain) gives me the same kind of error:
```
error[E0523]: found two different crates with name `pkg_config` that are not distinguished by differing `-C metadata`. This will result in symbol conflicts between the two.
 --> <anon>:1:81
  |
1 | #[allow(unused_extern_crates)] extern crate new; #[allow(unused_extern_crates)] extern crate old;
  |                                                                                 ^^^^^^^^^^^^^^^^^
```

**Comment by killercup** [comment] 2018-01-21 21:09
Steps to reproduce:

```bash
$ git clone https://github.com/joshtriplett/metadeps
$ cd metadeps
$ cargo upgrade -d error-chain # from cargo-edit
Upgrading error-chain v0.10 -> v0.11.0
$ cargo semver
[…]
error[E0523]: found two different crates with name `pkg_config` that are not distinguished by differing `-C metadata`. This will result in symbol conflicts between the two.
 --> <anon>:1:81
  |
1 | #[allow(unused_extern_crates)] extern crate new; #[allow(unused_extern_crates)] extern crate old;
  |                                                                                 ^^^^^^^^^^^^^^^^^
```

**Comment by ibabushkin** [comment] 2018-01-23 12:15
I see. I'll try to find a way to avoid this problem this week. I'm still unsure about the reasons it happens at this point, especially it's spurious nature is confusing. If anyone of you finds other (hopefully reproducible) cases, that'd be rather useful.

**Comment by ibabushkin** [comment] 2018-01-26 19:30
I pushed a commit that fixes the issue (at least in my local setup). Please confirm if all cases are caught (they should be, just to make sure).

**Comment by Eijebong** [comment] 2018-01-26 19:36
Yeah, this seems to be fixing this one :)

**Comment by ibabushkin** [comment] 2018-01-26 19:49
Alright, closing.

**Closed by ibabushkin** 2018-01-26 19:50 UTC
Labels: bug
